# nome da pipeline
name: run Basic Testes

# evento que dispara a pipeline
on:
  pull_request:
    branches: [staging]

# jobs da pipeline
jobs:
  # o que vai ser feito nessa pipeline
  cypress-run:
    # tipo de máquina que vai rodar a pipeline
    runs-on: ubuntu-latest

    # etapas da pipeline
    steps:
      # clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      # Setup Node (importante para versões específicas)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

        # exemplo de execução no terminal
      - name: instalar dependências
        run: npm ci

        # execução dos testes do projeto
      - name: Run testes
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

        # upload do relatório do mocha
      - name: upload relatório
        uses: actions/upload-artifact@v4
        with:
          name: Relatório
          path: cypress/reports